### PR TITLE
Swift4

### PR DESCRIPTION
**Pull request by pokryfka**
Ported to Swift4

### CODE REVIEW

**Comment by marcoconti83** [comment]
Hi @pokryfka! 
Thank you for your contribution and for taking the time to port this to Swift 4! 
The company where I work already has a Swift 4 fork (https://github.com/wireapp/targone/releases/tag/0.10) that was never ported back upstream to this repository. I will merge that fork into master and then I will check again how your pull request compare to master.

**Comment by marcoconti83** [comment]
It seems like the two repositories have been out of sync for a while. Also develop and master diverged. I will try to do some clean up and then come back to this.

**Comment by marcoconti83** [comment]
@pokryfka I merged everything back to master and merged back upstream from the fork. I updated the PR so that it points to master instead.

Could you please double check if the changes in the PR are still valid? Thanks for helping out!

**Comment by pokryfka** [comment]
Hi Marco,

Thanks for updating the main project.

No worries - If swift4 is supported now just reject my PR.

Cheers!
Michal

**Comment by marcoconti83** [comment]
I did some clean up, and now tagged the version that supports Swift 4: https://github.com/marcoconti83/targone/releases/tag/0.9

I will close this PR then. Thanks for raising the issue about Swift 4!

**Pull request closed without merging**
